### ISSUE TITLE
template-html-css-js 运行build 命令报错

### ISSUE THREAD

**Issue by dingliefr123** [heybran/create-webcomp#5]
您好 我也是一个对Web Components感兴趣的前端开发者。我是在B站发现您的项目的，国内关于WeB Components的资料很少，而您的视频和讲解我也受益匪浅，非常感谢。
问题是这样的，我单独运行了 `template-html-css-js` 这个项目（并没有运行整个REPO）。DEV 命令可以正常运行，但是 build 命令会报以下错误。请问您遇到过以下错误吗？
```shell
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> web-components-vite@0.0.0 build
> vite build

vite v4.5.0 building for production...
✓ 6 modules transformed.
✓ built in 149ms
[vite:build-html] Unable to parse HTML; parse5 error code unexpected-character-in-unquoted-attribute-value
 at C:/Users/Administrator/Desktop/template-html-css-js/src/components/my-app/index.html:1:31
1  |  export default "<div><a href=\"https://vitejs.dev\" target=\"_blank\"><img class=\"logo vite\" alt=\"Vite logo\"> </a><a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Web_components\" target=\"_blank\"><img class=\"logo vanilla web-components\" alt=\"Web Components logo\"></a><h1>Hello Vite & Web Components!</h1><div class=\"card\"><my-counter count=\"0\"></my-counter></div><p class=\"read-the-docs\">Click on the Vite or
Web Components logo to learn more</p></div>";
   |                                ^
file: C:/Users/Administrator/Desktop/template-html-css-js/src/components/my-app/index.html
error during build:
Error: Unable to parse HTML; parse5 error code unexpected-character-in-unquoted-attribute-value
 at C:/Users/Administrator/Desktop/template-html-css-js/src/components/my-app/index.html:1:31
1  |  export default "<div><a href=\"https://vitejs.dev\" target=\"_blank\"><img class=\"logo vite\" alt=\"Vite logo\"> </a><a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Web_components\" target=\"_blank\"><img class=\"logo vanilla web-components\" alt=\"Web Components logo\"></a><h1>Hello Vite & Web Components!</h1><div class=\"card\"><my-counter count=\"0\"></my-counter></div><p class=\"read-the-docs\">Click on the Vite or
Web Components logo to learn more</p></div>";
   |                                ^
    at handleParseError (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:37523:11)
    at Parser.onParseError (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:37449:13)
    at Tokenizer._err (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:1125:89)
    at Tokenizer._stateAttributeValueUnquoted (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:2687:22)
    at Tokenizer._callState (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:1632:22)
    at Tokenizer._runParsingLoop (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:1149:22)
    at Tokenizer.write (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:1174:14)
    at Function.parse (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:4856:26)
    at parse (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-f0c7dae0.js:7927:19)
    at traverseHtml (file:///C:/Users/Administrator/Desktop/template-html-css-js/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:37445:17)
```

**Comment by heybran** [comment]
您好，感谢您的支持和肯定，我刚才也测试了一下，出现和您同样的错误（非常抱歉，显然我当时没有测试`npm run build`命令，想当然的以为dev可以然后build就也可以)，可以这样解决，在import html的最后加上`?raw`，如下。

```javascript
// my-app/index.js
import html from "./index.html?raw";
// 其他代码
```

还有
```javascript
// my-counter/index.js
import html from "./index.html?raw";
```

我后来在这个项目中是这么使用的：https://github.com/heybran/cucumber-components/blob/main/src/components/dialog/dialog.js#L3

是的，国内谈Web Components的很少，我除了录制视频，其他时间一般混国外圈，和他们交流web components，您有兴趣， 可以加入Mastodon，上面非常多关于web components的讨论，这个是我的Mastodon: https://mastodon.online/@heybran

**Comment by wintful** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
tcheee, @classicclark, @wmh, @tdickman, @vlnk, @dogedogg, @TheLastFrame, @kpalang, @bshyong, @phxc, @calchulus, @0xObsidian, @isidorosp, @rlan, @n3x77, @maximedotair, @abra, @yoyashi, @ramazangur, @WeiLong27
